# Generated by Django 3.1.3 on 2021-04-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210421_2100'),
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='Contenders',
            field=models.ManyToManyField(blank=True, null=True, related_name='Contenders', to='Profile.Profile'),
        ),
    ]
