# Generated by Django 3.1.3 on 2021-04-22 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0002_auto_20210422_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='Check',
            field=models.FileField(upload_to='Check_File/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt']), django.core.validators.FileExtensionValidator(allowed_extensions=['cpp']), django.core.validators.FileExtensionValidator(allowed_extensions=['c']), django.core.validators.FileExtensionValidator(allowed_extensions=['java']), django.core.validators.FileExtensionValidator(allowed_extensions=['py'])]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Problem',
            field=models.FileField(upload_to='Problem_Statement/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt']), django.core.validators.FileExtensionValidator(allowed_extensions=['docx']), django.core.validators.FileExtensionValidator(allowed_extensions=['txt']), django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
