# Generated by Django 3.1.3 on 2021-04-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0004_auto_20210422_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='Problem',
            field=models.FileField(upload_to='<django.db.models.fields.CharField>_Problem_Statement/'),
        ),
    ]
