# Generated by Django 3.1.3 on 2021-04-22 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0005_auto_20210422_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='Check',
            field=models.FileField(upload_to='Check_File/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Dataset',
            field=models.FileField(upload_to='Dataset/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Problem',
            field=models.FileField(upload_to='Problem_Statement/'),
        ),
    ]
