# Generated by Django 3.1.3 on 2021-04-23 07:30

import Contest.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0007_contest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='Output',
            field=models.FileField(upload_to=Contest.models.content_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
