# Generated by Django 3.1.3 on 2021-04-23 07:52

import Contest.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0009_remove_submission_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='Check',
            field=models.FileField(upload_to=Contest.models.check_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Dataset',
            field=models.FileField(upload_to=Contest.models.dataset_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Problem',
            field=models.FileField(upload_to=Contest.models.problem_file_path),
        ),
    ]
