# Generated by Django 3.1.3 on 2021-04-23 11:31

import Contest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0011_auto_20210423_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='Check',
            field=models.FileField(upload_to=Contest.models.check_file_path),
        ),
        migrations.AlterField(
            model_name='contest',
            name='Problem',
            field=models.FileField(upload_to=Contest.models.problem_file_path),
        ),
    ]
