# Generated by Django 3.1.3 on 2021-04-20 18:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Age', models.IntegerField(validators=[django.core.validators.RegexValidator('([1]{1}[6-9]{1}|[2-5]{1}[0-9]{1}){1}', 'Age must be in the range of 16-59.', 'Age must be in the range of 16-59.')])),
                ('Phone', models.IntegerField(validators=[django.core.validators.RegexValidator('[1-9]{1}[0-9]{9}', 'Enter the phone number without 0 and country code.', 'Enter the phone number without 0 and country code.')])),
                ('Image', models.ImageField(default='Profile_Pictures/Default.png', upload_to='Profile_Pictures/')),
                ('Profession', models.CharField(choices=[('Student', 'Student'), ('Professional', 'Professional'), ('Decline to answer', 'Decline to answer')], max_length=20)),
                ('College', models.CharField(blank=True, max_length=200)),
                ('Level', models.CharField(choices=[('amateur', 'Amateur'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advance', 'Advance'), ('expert', 'Expert')], max_length=20)),
                ('Languages', multiselectfield.db.fields.MultiSelectField(choices=[('C/C++', 'C/C++'), ('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Object-C', 'Objective-C'), ('PHP', 'PHP'), ('Swift', 'Swift'), ('Ruby', 'Ruby'), ('Perl', 'Perl'), ('Go', 'Go'), ('R', 'R'), ('Scala', 'Scala')], max_length=68)),
                ('LinkedIn', models.URLField(blank=True, max_length=100)),
                ('GitHub', models.URLField(blank=True, max_length=100)),
                ('Rating', models.FloatField(default=0)),
                ('Histoty', models.TextField(default='No History')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
