# Generated by Django 3.1.3 on 2021-04-21 15:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Nickname',
            field=models.CharField(blank=True, default='Nick name', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C/C++', 'C/C++'), ('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Object-C', 'Objective-C'), ('PHP', 'PHP'), ('Swift', 'Swift'), ('Ruby', 'Ruby'), ('Perl', 'Perl'), ('Go', 'Go'), ('R', 'R'), ('Scala', 'Scala')], max_length=68),
        ),
    ]
