# Generated by Django 3.1.3 on 2021-04-23 07:52

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210421_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='Profile_Pictures/Default.png', upload_to=Profile.models.profile_file_path),
        ),
    ]
