# Generated by Django 3.1.3 on 2021-04-23 08:19

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20210423_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='Default.png', upload_to=Profile.models.profile_file_path),
        ),
    ]
